### ISSUE TITLE
extdb error - or did I screw something up?

### ISSUE THREAD

**Issue by Mike-Gracia-Digital** [RPFramework/RPFramework#14]
This looks like an interesting project!

Not sure if I've done something wrong, but using the default mission PBO, I get the following error in the RPT log:
`found in (560,422).
c:\w\stable\futura\lib\network\networkserver.cpp NetworkServer::OnClientStateChanged:NOT IMPLEMENTED - briefing!
 Mission id: 1af4ddb429cafa268ad95026e05bbe5f141c00de
Error in expression <, "SQL_CUSTOM_V2", "rpframework"] spawn ExternalS_fnc_ExtDBinit;
sleep 3;
[] cal>
  Error position: <ExternalS_fnc_ExtDBinit;
sleep 3;
[] cal>
  Error Undefined variable in expression: externals_fnc_extdbinit
File mpmissions\__cur_mp.Altis\init.sqf, line 10
Error in expression <ternalS_fnc_ExtDBinit;
sleep 3;
[] call Server_fnc_handleDisconnect;
[] spawn Se>
  Error position: <Server_fnc_handleDisconnect;
[] spawn Se>
  Error Undefined variable in expression: server_fnc_handledisconnect
File mpmissions\__cur_mp.Altis\init.sqf, line 12`

Any ideas what could be wrong?

The \sql_custom\rpframework.ini file 

`[Default]

Version = 1  
;; Used incase there is ever a breaking change, or to inform user in log about a new feature.

Strip Chars = ";[]"
;; List of characters to strip out  
Strip Chars Mode = 0
;; 0 = Strip Bad Chars, 1 = Strip + Log Bad Chars, 2 = Return Error & Log Bad Chars  
;;     Note: Logging on works when sending data to database.

; --------------------------------------------------------------------------------
; SQL Statements https://bitbucket.org/torndeco/extdb3/wiki/extDB3%20-%20sql_custom.ini
; --------------------------------------------------------------------------------

[existPlayerInfo]
SQL1_1 = SELECT CASE
SQL1_2 =    WHEN EXISTS(SELECT \* FROM users WHERE uid = ?)
SQL1_3 =           THEN 'true' ELSE 'false'
SQL1_4 = END;
SQL1_INPUTS = 1

[insertPlayerInfo]
SQL1_1 = INSERT INTO users (uid, name, items, clothes, pweapon, sweapon, cash, bank, cop, ems, position, garage) VALUES (?,?,?,?,?,?,?,?,?,?,?,?);
SQL1_INPUTS = 1,2,3,4,5,6,7,8,9,10,11,12

[updatePlayerInfo]
SQL1_1 = UPDATE users SET items=?, clothes=?, pweapon=?, sweapon=?, cash=?, bank=?, position=?, garage=? WHERE uid=?;
SQL1_INPUTS = 1,2,3,4,5,6,7,8,9

[playerInfo]
SQL1_1 = SELECT items, clothes, pweapon, sweapon, cash, bank, cop, ems, position, garage, bankaccount FROM users WHERE uid=?;
SQL1_INPUTS = 1

OUTPUT = 1,2,3-string,4-string,5,6,7,8,9,10,11

[updateUsersValueString]
Prepared Statement = false

SQL1_1 = UPDATE users
SQL1_2 =    SET $CUSTOM_3$ = "$CUSTOM_2"
SQL1_3 = WHERE uid = "$CUSTOM_1$;
SQL1_INPUTS = 3,1-mysql_escape,2-mysql_escape

`

**Comment by Mike-Gracia-Digital** [comment]
I noticed also that some of the code still seems to reference "extDB2", is this okay?

THanks - sorry if I've missed something obvious!

**Comment by kerkkoh** [comment]
Are you running the latest version with extDB3? I will look into this as soon as possible.

**Comment by superihippo** [comment]
Also make sure you are running the server with @RPF_Server enabled.

**Comment by kerkkoh** [comment]
@MikeThinkable Seems like you don't have the @RPF_Server enabled because the server sided functions aren't loading for the server.
