### ISSUE TITLE
Shops and the DB

### ISSUE THREAD

**Issue by DarkT3mplar** [RPFramework/RPFramework#21]
Hi there, I'm having an issue with the shop settings, I added the GPS and MAP, I can buy them and they reg in my DB, but as soon as you logout and back in they get deleted from the DB and player.
Also I see the lots of error in my .RPT

[arma3server_2016-12-02_17-39-08.txt](https://github.com/RPFramework/RPFramework/files/627979/arma3server_2016-12-02_17-39-08.txt)

**Comment by darderik** [comment]
It seems that the main AsyncCall handler is getting executed in an unscheduled environment,even if uisleep is getting used.



Try to merge the last commit of my [fork](https://github.com/DardoTheMaster/RPFramework), I just replaced the call command with the spawn one.

**Comment by DarkT3mplar** [comment]
TY will give it a go.

**Comment by DarkT3mplar** [comment]
your files fixed the inventory Items but now the bank and player money does the same thing.

**Comment by darderik** [comment]
Please could you post the logs ?

**Comment by kerkkoh** [comment]
The log spam hasn't cause problems so far but I will be fixing it in the new update if it is indeed causing trouble.

Problem with running the functions in a scheduled evironment was that some of the functions need an array that the database function returns and 'spawn' can't return it.

**Comment by darderik** [comment]
Oh, got it.
But removing the uisleeps may cause issues,as the connection with the db takes a bit of time

**Comment by kerkkoh** [comment]
Exactly, thus I've seen that the "log spam" has been necessary so far. I'll look into it.

**Comment by kerkkoh** [comment]
Fixed it with a somewhat crude duct tape solution, but at least it works.

If @DarkT3mplar could try the new version out and post the logs again if the issue persists.

**Comment by kerkkoh** [comment]
Looking back at this, this was a bug fixed in 4.1.0. Please make a new issue if you have more problems.
