### ISSUE TITLE
[Low Priority] Add Core Dialogs

### ISSUE THREAD

**Issue by darderik** [RPFramework/RPFramework#22]
I think that it would be nice to add some kind of cool dialogs to the core modules , this will improve surely the "look" of the whole framework

**Comment by kerkkoh** [comment]
I've left it like that so that anyone can edit them and make them, however, they want them to look like. I might consider doing this in the future though.

**Comment by darderik** [comment]
Then what about some kind of premade templates?

**Comment by kerkkoh** [comment]
As in some kind of psd files or what do you mean exactly?

**Comment by darderik** [comment]
Well actually I was thinking of some premade templates written in .hpp, but having psd files ready for use would be really useful for people that , like me , aren't that good in creating dialogs from scratches.

**Comment by kerkkoh** [comment]
There are some barebones .hpp dialogs included with the core. You can find them over at
`RPFramework/RPFramework.Altis/Dialogs/`
or just https://github.com/RPFramework/RPFramework/tree/master/RPFramework.Altis/Dialogs

If you got something more regarding this, please open a new issue!
