### ISSUE TITLE
Trunk of vehicles

### ISSUE THREAD

**Issue by Draxprod** [RPFramework/RPFramework#26]
Hello,

It's been several days since I have a problem, I can not find how to add and change the trunk of cars ...
Do you know how to change it?

Thank you in advance,

**Comment by kerkkoh** [comment]
How do you want to change it? In game, you can go to a car you own (the car is in RPF_Cars and it is local to your client) and use the TAB key by default to use the interaction system and click trunk. When you are carrying some physical item like a fishing net or delivery items, you will get an option to store it in the trunk. So in simple terms, the trunk is for stroring these 'physical items' (they need to be in the RPF_ownedFurniture array). 

If you need more help, you can join the discord server and come to the #support channel and I can give you live support.

**Comment by Draxprod** [comment]
I was talking about the capacity of the trunk of the vehicles and not the items .. For example the SUV can contain 7 items how to increase it or lower it?

**Comment by kerkkoh** [comment]
It's currently dependant on how much normal items the vehicle can hold, which is defined in CfgVehicles as "maxLoad". I divide that variable by 300 by default, but you could change it in the RPFramework mission/Functions/core/Vehicles/ open, take and -storeTrunk files. Now that I think of it, I should have probably change it to be a variable so people can easily change it. Will do this in the next update
