### ISSUE TITLE
Garage Not Storing Vehicles

### ISSUE THREAD

**Issue by jschmidt92** [RPFramework/RPFramework#28]
I bought two vehicles and stored both of them in the garage when I tried to retrieve them from the garage there's nothing listed to retrieve. Before I stored each vehicle in the garage I used the "Use Car Key" option to lock each vehicle. I checked the "rpframework.garage" table and nothing is saved in it as well.

**Comment by kerkkoh** [comment]
Seems like it's not just a database issue, I'll see what's up with this and try to fix it.

**Comment by kerkkoh** [comment]
id wasn't set to auto increment in garage. Fixed in 4.2.3
