### ISSUE TITLE
Medic Issue

### ISSUE THREAD

**Issue by ScripyZz** [RPFramework/RPFramework#29]
once a player die's and bleed's out you cant revive also if you shoot them then they die. dead body stays where it was before if you shoot it it will make them bleed out again when there alive. also keeps spawning 
money piles http://steamcommunity.com/sharedfiles/filedetails/?id=825732711 and you can go into the inventory of the money piles which will have the gear from his old dead body and you can take it.

**Comment by kerkkoh** [comment]
New medical module is going to be in 4.2.4, but still needs testing. Thank you for all the reports, I truly appreciate it!

**Comment by ScripyZz** [comment]
nope im gonna be testing everything mostly tomoz with my friend's about 3 people on test loads of stuff out

**Comment by ScripyZz** [comment]
ill will start recording aswell for the bugs with playstv so it explains it more

**Comment by kerkkoh** [comment]
Cool, I'll try to post the fixing versions for these issues tomorrow

**Comment by kerkkoh** [comment]
All three of your issues have been fixed. Thank you for reporting ❤️  https://github.com/RPFramework/RPFramework/releases/tag/4.2.4
