### ISSUE TITLE
Use Car Key

### ISSUE THREAD

**Issue by ScripyZz** [RPFramework/RPFramework#35]
Was at the car shop & i bought a suv. Then i unlocked it by using the Interaction menu using Use key and then i proceeded to get into the car  and i tried to get out and it was locked. So i had to use car key again

**Comment by ScripyZz** [comment]
I mean it unlocks automatically  when buying and once in the vehicle it locks itself

**Comment by kerkkoh** [comment]
This is because of the lock state, I'll work on fixing this.

**Comment by DaThrilelrKiller** [comment]
Idk what you mean by lockstste; however the lock command needs to be executed where the vehicle is local. It says it's a global command but in reality it is not.

**Comment by kerkkoh** [comment]
Will fix for the next version.

**Comment by kerkkoh** [comment]
If anyone stumbles upon this issue and wonders what it was about, the client had to be setOwner on the server just like mentioned earlier.
