### ISSUE TITLE
Translating strings to Brazilian Portuguese

### ISSUE THREAD

**Issue by psycodeliccircus** [RPFramework/RPFramework#36]
https://github.com/devcjax/RPFramework

@superihippo @theflyingjets @NiiRoZz @InnovativeStudios

**Comment by kerkkoh** [comment]
Cool! I'm going to intoduce stringtables in the future update to make translations a bit easier and I'll make sure to provide it asap for people to start translating.

**Comment by psycodeliccircus** [comment]
Thank you friend!
@superihippo
