### ISSUE TITLE
[Linux] Uppercased PBO (RPF_Server)

### ISSUE THREAD

**Issue by darderik** [RPFramework/RPFramework#40]
As stated in this [page ](https://community.bistudio.com/wiki/Arma_3_Dedicated_Server#Case_sensitivity_.26_Mods) , unfortunately Linux can't load pbos which contain capitals letters in their name. 
It would be nice to rename RPF_Server to rpf_server , consequently all the references to it, in order to allow an easier setup.
This obviously affects only Linux users.

**Comment by kerkkoh** [comment]
Will do. Thanks!

**Comment by kerkkoh** [comment]
RPF_Server is now rpf_server and so are all the mod pbos, just in case.
