### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by ghost** [RPFramework/RPFramework#41]
When is try and start my dedicated server (local TADST), i get this error: https://gyazo.com/4ba525ad0956dece803993a417feee05
When I try and start a AltisLifeServer, just to compare, it works fine. So it's something that happends when i try and launch with your framework.
I've tried reinstalling the runtime c++ program, but still doesn't work.

Don't know if you have any fixes to this, or i'm the only one?

Regards, ValleiE

**Comment by kerkkoh** [comment]
Hey,

This was something that appeared after the new Arma 3 updates and I haven't found any good way to solve it other than using the x64 server executable.

**Comment by ghost** [comment]
Now the server just crashed(stopped working). Thats wierd.
I'm going to try and see if i can fix it.

**Comment by kerkkoh** [comment]
Please post your client and server rpts and your extdb3 logs.

Also please check your version and make sure it's the latest version from GitHub or Dropbox.

Uninstall the Visual C++ Redistributable package (both x86 and x64 version), restart your computer and install the package again (do not use the Repair function).

**Comment by ScripyZz** [comment]
It's something todo with your system driver's

**Comment by ScripyZz** [comment]
Make sure to install the requirements for extdb3.

**Comment by ScripyZz** [comment]
@superihippo whats this about any clue? [Thread 4712] extDB3: SQL: Initialized: NULL = ""
 [Thread 4712] extDB3: Locked

**Comment by kerkkoh** [comment]
Go over to our Discord and ask Optix there. I can't currently provide support.

Closing since there hasn't been a response from the op.
