### ISSUE TITLE
[Fixed] This application has requested the Runtime to terminate it in an unusual way

### ISSUE THREAD

**Issue by harrisonclewis** [RPFramework/RPFramework#49]
Current version (Check VERSION.txt)
5.1.0 STABLE

Running a fresh install of RPFramework?
Yes

Describe the issue as well as you can below.
The server starts fine. When joining around half of the mission file downloaded the Arma3Server.exe closes and returns this error: https://gyazo.com/d5486b26de2e416c5ae664b35ff36bc7 OR "This application has requested the Runtime to terminate it in an unusual way".

Please leave your Arma 3 Server's RPT (Location depends on your launch params) and Client's RPT (AppData\Local\Arma 3)
https://pastebin.com/raw/NUU5EZSr - RTP
https://pastebin.com/raw/ehdDLzrv - Client RTP

**Comment by harrisonclewis** [comment]
Fix found: https://github.com/RPFramework/RPFramework/issues/41
Please ignore this thread it is a duplicate.

**Comment by kerkkoh** [comment]
Check your extDB3 logs for errors since this is related to extDB3.
