### ISSUE TITLE
Fishing net kills

### ISSUE THREAD

**Issue by OfficialXtreme** [RPFramework/RPFramework#5]
This is fairly obvious, not aware if it's fixable, but fishing nets are lethal fuckers haha, basically, a player can walk into your net whilst your carrying it and poof they die

**Comment by kerkkoh** [comment]
Can't come up with anything that would fix this right now other than making a new array of objects that are currently attached to players and then on join disable every player's collision with them and of course run this on a loop ==> A bad idea in terms of performance.

**Comment by NiiRoZz** [comment]
use https://community.bistudio.com/wiki/disableCollisionWith not need to use loops

**Comment by kerkkoh** [comment]
Takes logal arguments so you would have to run it for each player and make it JIP friendly so loops needed

**Comment by NiiRoZz** [comment]
Not loups just use remoteExec With jip true and it's finish

**Comment by NiiRoZz** [comment]
Command : 
[_Fishingnet, {_this disableCollisionWith player}] remoteExec ["call", 0, true];

**Comment by kerkkoh** [comment]
Only concern is that you have to also enable collision and this would stack JIP statements

**Comment by NiiRoZz** [comment]
So use handledamage event handler and return 0 damage when it's object
just need to check when you killed by fishing net return fishing net or nothing

**Comment by kerkkoh** [comment]
Want to code this in or should I have some fun xD? @NiiRoZz

**Comment by NiiRoZz** [comment]
I Will

**Comment by kerkkoh** [comment]
I think handledamage doesn't give you the object classname when the damage is caused by physx collision so that's why the handledamage method didn't work. I'll try to figure something out for 4.0.0, I will still take suggestions before release.

**Comment by kerkkoh** [comment]
Issue should be fixed in the next update.

Open a new issue if this still happens.
