### ISSUE TITLE
"Loading in" Issue

### ISSUE THREAD

**Issue by Exodoos** [RPFramework/RPFramework#53]
C**urrent version:**
5.1.0 STABLE (DEV-Branch)

**Running a fresh install of RPFramework?**
Yes for the first Time.

**Describe the issue as well as you can below.**
When I enter the server, the error comes, which still loads extDB3.

**LOGS:** 
Server RPT Log:
https://pastebin.com/tAxgK7kM

Client RPT Log:
https://pastebin.com/pCuMXFdu

extDB3 Log:
https://pastebin.com/wNgTZ13H

**Comment by OptixA3** [comment]
Send you ExtDB3 Logs. Also, remove the optional folder in @ExtDB3 that Kerkohh left in because he's a silly fool.

**Comment by kerkkoh** [comment]
OP try to repack the pbos since you're using the dev branch. The dev branch doesn't have a bin folder that is up to date. You could also just switch to the master branch and make your life a bit easier. Also make sure to use the unmodified mission and server files.

**Comment by KifKick** [comment]
It looks like on server your server mod is not loading. Mission is trying to call server function but function is not defined. Check your pbo in RPF_Server.

**Comment by kerkkoh** [comment]
Issue seems to have been solved as OP hasn't responded here nor on the discord channel where we tried to help him out.
/closed
