### ISSUE TITLE
Server Side Localization

### ISSUE THREAD

**Issue by darderik** [RPFramework/RPFramework#55]
As the server language will always be English, localizing strings server side and then passing them to client will result in incorrect messages, and in the specific case of the ShopSystem module , broken shops.

Involved Files:
[rpf_server/stringtable.xml](https://github.com/RPFramework/RPFramework/blob/master/%40RPF_Server/addons/rpf_server/stringtable.xml)

[rpf_server/config.hpp](https://github.com/RPFramework/RPFramework/blob/master/%40RPF_Server/addons/rpf_server/Functions/modules/ShopSystem/config.hpp)

[RpFramework.Altis/Functions/Modules/ShopSystem/fn_openVirtualShop](https://github.com/RPFramework/RPFramework/blob/master/RPFramework.Altis/Functions/modules/ShopSystem/fn_openVirtualShop.sqf#L33) (Comparing server side localized strings with local localized ones)

**Comment by kerkkoh** [comment]
https://github.com/RPFramework/RPFramework/commit/8f2cad7e7aedc0eedfacdf8594199b3feb28ac06
