### ISSUE TITLE
Spawn Issues

### ISSUE THREAD

**Issue by OfficialXtreme** [RPFramework/RPFramework#6]
Issue with spawning, sometimes players will Spawn with a map etc, and other times they will not.

**Comment by kerkkoh** [comment]
Would be solved by making a module that resets and adds player a default bunch of gear when respawning (EH?).

**Comment by NiiRoZz** [comment]
I think need to put Eventhandler "Respawn" and add base stuff

**Comment by theflyingjets** [comment]
I agree with superihppo

**Comment by kerkkoh** [comment]
This issue will be closed since it will be solved after the 4.0.0 release.
