### ISSUE TITLE
Server_fnc_hand;leDisconnect

### ISSUE THREAD

**Issue by Stevekovix** [RPFramework/RPFramework#80]
Current version (Check VERSION.txt)

7.0.1 STABLE

Running a fresh install of RPFramework?

Yes

Describe the issue as well as you can below.

The server don't want to start :/ Just a black screen

Please leave your Arma 3 Server's RPT (Location depends on your launch params), Client's RPT (AppData\Local\Arma 3) and ExtDB3 Log (Arma 3\@extDB3\logs\year\month\day) here, preferably pasted in pastebin or gist, do not paste them here!

I just give u the lines with the errors

RPT server :

 2:48:58 "---------------------------------------------------------------------"
 2:48:58 "---------------------------------------------------------------------"
 2:48:58 CallExtension loaded: extDB3 (E:\Arma 3 DEV Quatum\@extDB3\extDB3.dll) [ȁ4(�@]

 2:48:58 "extDB3 Loaded"
 2:48:58 "---------------------------------------------------------------------"
 2:48:58 "---------------------------------------------------------------------"
 2:48:58 Connected to Steam servers
 2:48:59 c:\bis\source\stable\futura\lib\network\networkserver.cpp NetworkServer::OnClientStateChanged:NOT IMPLEMENTED - briefing!
 2:48:59  Mission id: b6998e86e8628acd4e75b3ab053db7d16fdab063
 2:48:59 Attempt to override final function - bis_fnc_storeparamsvalues_data
 2:48:59 Error in expression <iSleep 1;

if (isServer) then {
[] call Server_fnc_handleDisconnect;
[] spawn Se>
 2:48:59   Error position: <Server_fnc_handleDisconnect;
[] spawn Se>
 2:48:59   Error Undefined variable in expression: server_fnc_handledisconnect
 2:48:59 File mpmissions\__cur_mp.Altis\init.sqf, line 10
 2:49:00 BEServer: registering a new player #1242245056
 2:49:22 Unaccessible
 2:50:21 Client: Remote object 3:0 not found
 2:52:08 Deinitialized shape [Class: "C_Soldier_VR_F"; Shape: "a3\characters_f_bootcamp\common\vr_soldier_f.p3d";]
 2:52:08 Deinitialized shape [Class: "C_man_polo_2_F"; Shape: "a3\characters_f\civil\c_poloshirt.p3d";]
 2:52:08 c:\bis\source\stable\futura\lib\network\networkserver.cpp ClearNetServer:NOT IMPLEMENTED - briefing!
 2:52:09 Extensions:
 2:52:09   extDB3 (E:\Arma 3 DEV Quatum\@extDB3\extDB3.dll) [ȁ4(�@]

Extdb3 Log : Nothing wrong in :)

**Comment by kerkkoh** [comment]
Server PBO is not loaded. Make sure to start the server with @rpf_server mod and make sure that there is indeed a PBO inside a3folderwhatever\@rpf_server\addons and not a folder. If the issue persists, please repack the PBO using any PBO packing tool and replace the old one with it.

You can also find the newest @rpf_server from the bin folder within the repository.

If you still have an issue, please post FULL logs pasted on Pastebin or any other paste website.

You can also reach us on our discord and get help within 12-24 hours most of the time.

Thank you!

**Comment by kerkkoh** [comment]
I'm going to assume this issue is solved.
