### ISSUE TITLE
* Not issue * : Proposals

### ISSUE THREAD

**Issue by NiiRoZz** [RPFramework/RPFramework#9]
Hello, i'm developer of Altis Life : 

First : Nice job. It's really nice to add module ect ...
Two : For optimization and scurity don't use BIS_fnc_MP, use Remoteexec. RemoteExec are more rapid and secur and all of that
Three : Just for you, take the last Asynccall here : https://github.com/ArmaLife/Framework/blob/master/life_server/Functions/MySQL/fn_asyncCall.sqf  
Fixed bug of the first ascynccall
Four : Use loops : for "_i" from 0 to 1 step 0 do instead of while loops for opimization 
Five : use CursorObject instead of cursorTarget
Six : If you want any help, i can help you no problem.

**Comment by kerkkoh** [comment]
1. Thank you so much :)
2. Doesn't that need a whitelisting config or something? I need to really take a look at that and learn how it works.
3. That script includes "\life_server\script_macros.hpp", do I need to take something from there?
4. Is for actually faster than while?
5. Need to take a look at that
6. Coolio :D If you want to do some fixes or anything, just fork it and pull request and I'll merge it :D

**Comment by NiiRoZz** [comment]
1. Yes need config but easy to config something just try to look inside wiki of boehmia
2. i Have pull request the last with all change
3. Yes.
4. Use stringtable i think it's nice for anyone want translate any message, it's long to do all but for support all message inside your mission. If you want help to translate in french i'm here

**Comment by NiiRoZz** [comment]
I have one question why you use extdbquery and use extdbasync i think use only Async

**Comment by kerkkoh** [comment]
While coding the backend I had problems with async not doing what I wanted and I was tired of debugging the problem so I coded my own alternative that did exactly what I needed it to do lol.

**Comment by kerkkoh** [comment]
Just did an update to ExtDB3 and I just switched to the async supplied by Torndeco. If you have any changes to it could you do a pull request? @NiiRoZz

**Comment by NiiRoZz** [comment]
@superihippo Just put the same as before : it's the same or i pull request it if you want

**Comment by kerkkoh** [comment]
Are you @NiiRoZz on twitter? Just thought about it when I mentioning you for the new update.

**Comment by NiiRoZz** [comment]
Yes i Will check, and i Will speak you if it's me

**Comment by NiiRoZz** [comment]
send me your twitter i will follow you because i don't have any notfication

**Comment by kerkkoh** [comment]
@Superihippo, I followed you.

**Comment by NiiRoZz** [comment]
@superihippo I followed you too
